image: node:slim
before_script:
  - apt-get update && apt-get -y install fontforge
  - npm config set loglevel warn && npm set progress=false
  - npm install -g gulp --loglevel=warn
  - cd ./wp-content/themes/barrel-base
  - npm install --loglevel=warn
stages:
  - build
  - test
job1:
  stage: build
  only:
    - master
  script:
    - gulp build
job2:
  stage: test
  script:
    - gulp validate