image: node:6
before_script:
  - apt-get update && apt-get -y install fontforge findutils
  - npm config set loglevel warn && npm set progress=false
  - npm install -g gulp --loglevel=warn
  - cd ./wp-content/themes/barrel-base
  - npm install --loglevel=warn
stages:
  - test
  - build
php_syntax_check:
  stage: test
  script: 
    - apt-get install -y php7.0
    - which php
    - "git diff --name-only origin/master | grep .php | xargs -L1 php -l"
js_lint:
  stage: test
  script: "gulp validate"
build:
  stage: build
  only:
    - master
  script: "gulp build"
