stages:
  - test
  - deploy
  - merge_request
image: barrelny/multipurpose-ci:0.0.11
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - wp-content/themes/$THEME_NAME/node_modules/
test_grammars:
  stage: test
  before_script:
    # @todo: move script to bash with proper exit
    # @todo: install standard globally to CI image
    # @todo: install editorconfig-checker globally to CI image
    # @todo: install stylelint globally to CI image
    - npm config set loglevel warn && npm set progress=false
    - npm install -g standard --loglevel=warn
  script: 
    - bash private/scripts/test_grammars.sh
  retry: 2
test_modules:
  stage: test
  script: 
    - bash private/scripts/test_modules.sh
  retry: 2
multidev_deploy:
  only: 
    - /(develop|feature|bugfix|hotfix)\/?(.*)/
  stage: deploy
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - bash private/scripts/import_git_remote.sh
  script:
    - bash private/scripts/multidev_deploy.sh
multidev_remove:
  only:
    - /^(feature|bugfix|support)\/.*/
  stage: deploy
  when: manual
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - bash private/scripts/import_git_remote.sh
  script:
    - bash private/scripts/multidev_remove.sh
create_merge_request:
  stage: merge_request
  only:
    - /^(feature|bugfix|support)\/.*/
  when: manual
  script:
    - ./private/scripts/merge_request.sh
