name: Test CLI commands

on:
  push:
    branches:    
      - master
  pull_request:
    branches:    
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 11.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, lint and test
      run: |
        npm ci
        npm run lint
        npm run start -- --site=wordpress-at-scale
      env:
        CI: true
    - name: Archive BackstopJS artifacts
      uses: actions/upload-artifact@v1
      with:
        name: backstop_data
        path: backstop_data
    - name: Upload BackstopJS artifacts
      uses: actions/upload-artifact@master
      with:
        name: backstop_data
        path: backstop_data
